name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '21.7.1'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build